name: MSBuild

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    permissions:
      contents: read
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=Release .
